--- #YAML:1.0
name:                perl-kolab
version:             2.2.4
abstract:            perl-kolab provides a basic set of perl modules required for the
Kolab Groupware server.
license:             ~
author:              
    - Stuart Bingë and others (see AUTHORS file)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
